apiVersion: v1
kind: Pod
spec:
  containers:
  - name: shell
    image: tongueroo/demo-jenkins-worker
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
