apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    role: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: <%= dockerfile_port %>
  selector:
    role: web
  type: ClusterIP
